version: '3.3'
services:
  result:
    environment:
      - PG_HOST
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    command: ['npm', 'start']
    volumes:
      - .:/usr/src
    working_dir: "/usr/src"
    ports:
      - "5001:80"
      - "5858:5858"
    image: node:6-alpine
    restart: on-failure:5

  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data1:/var/lib/postgresql

  inventory-service:
    image: docker.io/etbe/inventory
    volumes:
      - ./inventory/contract-interface.yaml:/app/contract-interface.yaml
    ports:
      - "1350:1350"

volumes:
  db-data1:

