version: "2"

services:
  result:
    environment:
      - PG_HOST
    working_dir: /usr/src
    command: ['npm', 'start']
    volumes:
      - .:/usr/src
    ports:
      - "5001:80"
      - "5858:5858"
    image: node:6-alpine
    restart: on-failure:5

volumes:
  db-data:
